### ISSUE TITLE
toPromise is deprecated FYI

### ISSUE THREAD

**Issue by joshribakoff** [re-rxjs/react-rxjs#100]
https://github.com/ReactiveX/rxjs/blob/c9ea2b0fd45d6ca41ab8370231ee1a2503757fa9/src/internal/Observable.ts#L460

**Comment by josepot** [comment]
It will be deprecated on v7, which hasn't been released yet. [It's not deprecated on v6](https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/Observable.ts#L349-L363) and if you look at the expected version on our peer-dependencies you will notice that's not a problem.

**Comment by joshribakoff** [comment]
Ah makes sense thanks for clarifying
