### ISSUE TITLE
new util: newInput

### ISSUE THREAD

**Issue by josepot** [re-rxjs/react-rxjs#126]
Admittedly, creating input streams is a lot of boilerplate. I remember that @rikoe mentioned it once and I agree: it's quite tedious. So, I'm thinking about adding the following util:

```ts
const newInput = <A extends unknown[], T>(                  
  mapper: (...args: A) => T,                                   
): [Observable<T>, (...args: A) => void] => {                  
  const subject = new Subject<T>()                             
  const onEvent = (...args: A) => subject.next(mapper(...args))
  return [subject.asObservable(), onEvent]                     
}                                                              
```

either that, or:

```ts
const newInput = <A extends unknown[], T>(                  
  mapper: (...args: A) => T,                                   
): [Subject<T>, (...args: A) => void] => {                  
  const subject = new Subject<T>()                             
  const onEvent = (...args: A) => subject.next(mapper(...args))
  return [subject, onEvent]                     
}                                                              
```

Should we add it? And if we do, which one do you prefer: the one that exposes the `Subject` or the one that just exposes an `Observable`?

An example:

before:
```ts
const add$ = new Subject<string>()                                
const onAdd = (text: string) => text && userAdd$.next(text)

const edit$ = new Subject<{ id: number; text: string }>()
const onEdit = (id: number, text: string) => userEdit$.next({ id, text })                               
```
after:
```ts
const [add$, onAdd] = newInput((text: string) => text)
const [edit$, onEdit] = newInput((id: number, text: string) => ({ id, text }))
```

**Comment by voliva** [comment]
💯 That's a great idea. I've also found out this adds a bit of boilerplate, so it's nice to have an util for it.

I would go exposing an Observable. This is the only bit that adds a layer of indirection on a re-rxjs codebase, so I think it would be important to separate the consumer from the producer. This way it would be easy to find the consumers or the producers by just looking at the references of each value returned (e.g. edit$ and onEdit)

**Comment by rikoe** [comment]
Love it. Can you show an example of how this is actually hooked up to a component please, just for my n00b self.

I agree with @voliva - subjects are internal magic helpers 😉 , expose an observable.

I would think a bit more about the name "newInput" this isn't very descriptive to me. But I can't think of something better right now.

**Comment by rikoe** [comment]
What about "captureInput"?

**Comment by josepot** [comment]
> Love it. Can you show an example of how this is actually hooked up to a component please, just for my n00b self.

Sure:

```ts
const [click$, onClick] = newInput()
const [useCount] = bind(click$.pipe(
  map((_, idx) => idx + 1),
  startWith(0),
))

const Counter = () => {
  const count = useCount()
  return (
    <p onClick={onClick}>Click to increase {count}</p>
  )
}
```

> What about "captureInput"?

TBH I would prefer something shorter.

> I agree with @voliva - subjects are internal magic helpers 😉 , expose an observable.

💯  If for whatever reason the consumer needs the underlying Subject, then they shouldn't be using this util.

> I would think a bit more about the name "newInput" - this isn't very descriptive to me. But I can't think of something better right now.
> What about "captureInput"?

I would prefer something less verbose/shorter.
