### ISSUE TITLE
When an Observable emits a function

### ISSUE THREAD

**Issue by ilikejames** [re-rxjs/react-rxjs#152]
Upgrading from `@react-rxjs/core@0.2.0` -> `@react-rxjs/core@0.5.0` came across this regression. 

When an observable returns a function, we get a stringified (plus evaluated!) version of the function. This worked in the prior version.

```ts

const counter$ = timer(0, 1000).pipe(startWith(0), shareReplay(1));

const [useBoundMethodThatDoesntWork] = bind(() =>
  counter$.pipe(
    map((count) => {
      return (s) => `${s}: ${count}`;
    })
  )
);

// .....


const method = useBoundMethod();
method('a') // -> Not a function
typeof method // -> 'stirng'
return ({method})
  // -> function (s) { return "".concat(s, ": ").concat(count); }: 0:
```
[Code](https://codesandbox.io/s/observable-that-returns-a-function-2vilq?file=/src/App.js)

**Comment by josepot** [comment]
Hi @ilikejames ,

This issue[ is fixed on  `0.6.1`](https://codesandbox.io/s/observable-that-returns-a-function-forked-x1o55?file=/src/App.js). However, we will be publishing a patch for `0.5` shortly and I will add some tests to make sure that this doesn't happen again. Thanks a lot for reporting this!
