### ISSUE TITLE
Code examples use deprecated API members

### ISSUE THREAD

**Issue by hoclun-rigsep** [re-rxjs/react-rxjs#208]
I volunteer to update the code examples and the documentation.

**Comment by voliva** [comment]
Hey, thanks for raising this up!

We are currently remaking the docs from the ground up, you can follow the process in here -> https://github.com/re-rxjs/react-rxjs.org/issues/37

One of the main reason is that we want to make them easier to follow for newcomers, with less literature and more short recipes. Progress has been slow lately, but we're planning on picking up the pace soon.

You're very welcome to contribute, it is much appreciated! Either by updating things from the current docs which might be miss-leading or new suggestions/ideas for the new docs (or any kind of contribution, really 😃 ).
