### ISSUE TITLE
Unusual spelling for selfDependant()

### ISSUE THREAD

**Issue by hoclun-rigsep** [re-rxjs/react-rxjs#212]
There's no accepted English word spelled "dependant"—may want to consider renaming, possibly to `selfDependent()`

**Comment by josepot** [comment]
We will address this in the next release, for sure! Thanks a lot for letting us know it!

**Comment by josepot** [comment]
FYI: https://www.merriam-webster.com/words-at-play/spelling-variants-dependent-vs-dependant

I still think that it makes sense to rename it to `selfDependent` b/c American English is the predominant one while programming, eg: "color", "BehaviorSubject", etc
