### ISSUE TITLE
Typescript integration issues

### ISSUE THREAD

**Issue by cabello** [re-rxjs/react-rxjs#233]
Hi @josepot , how you doing? I hope you are doing great 😄 

This is somewhat related to #228.

While doing minor release updates:
<img width="342" alt="Screen Shot 2021-11-15 at 7 50 26 PM" src="https://user-images.githubusercontent.com/60936/141875720-3b62e7f5-b839-4eff-926e-e3417a172f30.png">

My Typescript app broke:
<img width="1030" alt="Screen Shot 2021-11-15 at 7 50 54 PM" src="https://user-images.githubusercontent.com/60936/141875753-a9b1edca-2394-4c6d-bf3b-87e53ae4f523.png">

Apparently Typescript does not support `mjs` yet so webpack customization is required in this case: https://github.com/formatjs/formatjs/issues/1395

Was that intentional? I.e. the fact that the library now breaks with Typescript?

Ideas, suggestions on how to bypass that? I think writing a custom rule saying mjs is still js is the most promising solution: https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361

Have a good one,

**Comment by josepot** [comment]
Hi @cabello !

Thanks for reporting this! I _think_ that we addressed this issue already, but it looks like we forgot to publish the patch for `@react-rxjs/utils@0.8.X`. Could you please try using `@react-rxjs/utils@0.9.3` (there shouldn't be any breaking changes...) and let us know if that solves the "compiling" issue? If it does, then I will publish a `@react-rxjs/utils@0.8.4` patch for this issue.

Thanks again!
