### ISSUE TITLE
Uncaught Error: Missing Subscribe

### ISSUE THREAD

**Issue by mbret** [re-rxjs/react-rxjs#270]
Hello, I am getting this error whenever I use bind() without the second parameter (default value).

Even a simple 

```
const [useFoo] = bind(of(1))

const Foo = () => {
  useFoo()
}
```

triggers the error.

```
const [useFoo] = bind(of(1), any)
```

this works however

**Comment by danizord** [comment]
@mbret you have to either use `<Subscribe>` or pass a default value: https://react-rxjs.org/docs/core-concepts#streams-as-state
