### ISSUE TITLE
takeUntil operator cannot complete a StateObservable

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [re-rxjs/react-rxjs#291]
# Description

The `takeUntil` operator doesn't work when applied on a StateObservable.

# Playground

To demo the bug, I have created the following playground: https://codesandbox.io/s/react-rxjs-bug-takeuntil-1-d69w72
You should expect the counter to stop incrementing when pressing the `STOP` button.

# Environment

rxjs 7.6.0
@react-rxjs/core 0.10.3
@react-rxjs/utils 0.9.5
react 18.2.0

**Comment by voliva** [comment]
Fixed at @react-rxjs/core@0.10.4
