### ISSUE TITLE
Server side rendering is missing `getServerSnapshot`

### ISSUE THREAD

**Issue by ink-su** [re-rxjs/react-rxjs#292]
Hi hi, this library looks very cool.

I tried this example https://react-rxjs.org/docs/getting-started#create-a-hook-from-an-observable with SSR using NextJS.

The following error shows up. 
`Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

Would it be possible to put add a way to set a default value as the third argument to: `useSyncExternalStore`?

**Comment by Jimmy89** [comment]
I had the same issue and I figured out I forgot to add the Subscribe wrapper around my parent jsx component.

For example:
```
import { Subscribe } from "@react-rxjs/core"

function Root() {
  return (
    <div>
      <Subscribe>
        <ChildWithBindedObserver />
      </Subscribe>
    </div>
  )
}

```

**Comment by ink-su** [comment]
Oops  I missed that 👍 Thanks for the tip
