### ISSUE TITLE
Subscribe incorrectly rendering fallback on initial mount

### ISSUE THREAD

**Issue by pkpbynum** [re-rxjs/react-rxjs#300]
Hi there, great library! I'm having an issue with the rendering lifecycle of `Subscribe`. In the [core concepts](https://react-rxjs.org/docs/core-concepts) you mention a drawback of `shareReplay` is that it keeps the last value around in memory--that is actually my desired behavior. e.g. if I navigate from page A -> B -> A, I'd like to hydrate A with the old data immediately and refetch new data in the background. I believe this is the model used by many other data fetching libraries (e.g. react query).

To work around this, I just piped a `shareReplay` into my observable, but `Subscribe` still isn't picking up on that latest value. On initial mount, it still renders the fallback component for a split second. A reproducible example is [here](https://codesandbox.io/s/pensive-lewin-fypwnp?file=/src/useTodos.ts).

Is there a way I can achieve this? Or is this a bug with `Subscribe`'s initial state?

**Comment by josepot** [comment]
> Is there a way I can achieve this? Or is this a bug with Subscribe's initial state?

Of course! Just keep a subscription always open, and then it will always have the latest value in memory. I.e: subscribe to the observable, right after defining it.

**Comment by voliva** [comment]
`<Subscribe>` always guarantees that it will have subscribed to the source observables *before* any of its children is rendered. This is something that's needed to prevent lingering subscriptions, specially with React with concurrent mode.

The way it does this is by first rendering nothing (or the fallback) on initial render, subscribing to the sources, and _then_ rendering the children passed to it.

If you want to avoid this double-render you'll have to manage the subscriptions further up: Don't use `<Subscribe>` at that level, instead declare an observable that will subscribe to all the streams your components need (a `merge` usually does the trick) when they are needed to become active, and subscribe to this observable further up on your tree.

**Comment by pkpbynum** [comment]
I think I understand the points you both are making. My point is that an observable with `shareReplay` should have it's last (aka "stale") value available synchronously in the initial mount, and the fallback should never be rendered. It should render the stale value until the next value is observed. This is the stale-while-revalidate paradigm. It seems to me that react-rxjs is doing _nothing_-while-revalidate. If this isn't the goal of this library I understand.

To @voliva's point, I'll try to raise my Subscribe up my react tree, but I think this isn't quite the behavior I want. If I do that, then the subscription's lifetime is no longer tied to where the data is needed in the react tree. Also--if I understand correctly--if there's an error, I'd need to remount that entire tree to start the subscription again.

**Comment by josepot** [comment]
> My point is that an observable with shareReplay should have it's last (aka "stale") value available synchronously in the initial mount

Not necessarily, no. Just because an Observable has been enhanced with `shareReplay`, that doesn't guarantee that the Observable will emit synchronously. It will only emit synchronously after it has emitted its first value, as long as all its listeners stay subscribed... However, the first value can come at any point in time, if it ever comes.

> My point is that an observable with shareReplay should have it's last (aka "stale") value available synchronously in the initial mount, and the fallback should never be rendered

Even if that was true (which it isn't) the only way to access that value is through a subscription, and since subscribing to an Observable it's a side-effect, it's something that can't be done on the render phase of the component. Therefore, there is no way to actually access the "current" value of a `shareReplay` Observable during the render function. That's why in this library we have had to come up with these `StateObservable`s, so that we can work around these short-comings (or trade offs, depends who you ask) of React.

> This is the stale-while-revalidate paradigm. It seems to me that react-rxjs is doing nothing-while-revalidate. If this isn't the goal of this library I understand.

We've most definitely failed at explaining the goals and the trade off of our library. Not your fault, of course. We should really improve our docs and explain these things better.

**Comment by voliva** [comment]
> To @voliva's point, I'll try to raise my Subscribe up my react tree, but I think this isn't quite the behavior I want. If I do that, then the subscription's lifetime is no longer tied to where the data is needed in the react tree. Also--if I understand correctly--if there's an error, I'd need to remount that entire tree to start the subscription again.

In theory it's posible to do the same behaviour you want, without relying on React's render cycle, but it's more tedious than just using `<Subscribe>` on the place you wanted.

`<Subscribe>` has this limitation that it will do that double render. In some cases that's not bad, but on others it is annoying... and the solution is to not use Subscribe there. You can move it to the nearest place where it doesnt get unmounted/remounted, and declare how that subscription is managed passing in the `source$` prop.

I've modified your sandbox to better show you what I mean: https://codesandbox.io/s/elegant-feather-fw2vjs?file=/src/App.tsx
On these cases it gets more tedious, as React-RxJS can't really circumvent the limitations of React when it comes to execution of side-effects (such as creating a subscription).

If you need error handling, this is something you can also add to your custom subscription management. For this, `retry({ delay: () => anotherObservable$ })` is usually very useful: It prevents the error from being propagated into the `<Subscribe>`, and re-subscribes to the observable when you declare it to.
