### ISSUE TITLE
`<Subscribe>` without `source$` does not seem to work as advertised

### ISSUE THREAD

**Issue by jyssh** [re-rxjs/react-rxjs#308]
The documentation [here](https://react-rxjs.org/docs/core-concepts) says:

> Subscribe also subscribes to all the observables used by its children (as if it were a React's Context), so in this case we can just omit source$

> Keep in mind that <Subscribe> will hold a subscription to the observables until it gets unmounted, ...

But the above does not seem to work.

I have set up a GitHub repo to demonstrate the issue: https://github.com/jyssh/react-rxjs-subscribe-problem/. 

To run the repo, do `npm ci` followed by `npm run dev`. Alternatively, this [codesandbox](https://codesandbox.io/p/sandbox/romantic-boyd-2ypd3f) should run the app right away.

As described in the repo's README:

> `<Subscribe>` wraps two screens - `<SelectCropScreen>` and `<One>`. Check the `Yield.jsx` file to verify.
> So any subscriptions made in both these screens - `<SelectCropScreen>` and `<One>` - should have been retained. But that does not happen.
> `<Subscribe source$>` works as intended though.

**Comment by voliva** [comment]
That same paragraph starts with a key point:

> **If you don't give it a default value**, you will need to make sure that observable has a subscription active before the Component that uses that hook is called.

The behaviour that `<Subscribe>` has regarding auto-subscribing to states only applies for those that doesn't have a default value.

If the state has a default value, then the component doesn't need that state to have a subscription active when it renders, so `<Subscribe>` will not subscribe to it.

If you need that state to have a subscription open, you can use the `source$` parameter, as you have already mentioned.

**Comment by jyssh** [comment]
Ok. My use case is a multi-step (or multi-"page") form, throughout which I need to keep several state-streams - each associated with an input - alive.

However, the components subscribed to those state-streams would come and go as the form changes its step/page. But I would like to those state-streams retain their values and not reset to 0 (when the subscriptions to them reach 0).

I see `<Subscribe>` as a way to keep subscriptions to those streams alive while the page under the `<Subscribe>` keep switching.

Is this way of using `<Subscribe>` correct?

If not, then is there another way to achieve my purpose?

**Comment by jyssh** [comment]
> If you do require an open subscription for that state, you can make use of the source$ parameter, as you've already noted.

If `<Subscribe source$>` is the only way, then in order to keep >1 state-streams alive, I imagine I would have to merge those streams into one, and use that merged stream as the `source$`. Correct?

**Comment by voliva** [comment]
> If <Subscribe source$> is the only way, then in order to keep more than 1 state-streams alive, I imagine I would have to merge those streams into one, and use that merged stream as the source$. Correct?

Yes, exactly. The auto-subscribing feature of `Subscribe` was added in the `0.8.0` release. Before that, you would have to merge all of your streams and pass them manually to the `source$`.

After 0.8.0 `source$` became optional, and it works great for the vast majority of cases. However, there are still some cases where you still need to manage your subscriptions manually... Either because you want to activate them regardless if a component is mounted or not, or to avoid the double-render that `Subscribe` does when mounting for the first time (and maybe other cases I haven't found yet).

**Comment by voliva** [comment]
You can also do `bind(someObservable$.pipe(startWith("")))`

**Comment by jyssh** [comment]
That works! Thank you for this library and your prompt response.
