### ISSUE TITLE
ESLint rule to prevent `connectObservable` and `connectFactoryObservable` being used inside components

### ISSUE THREAD

**Issue by josepot** [re-rxjs/react-rxjs#44]
I think that a common pitfall that new-comers will experience is that they may inadvertently use `connectObservable`/`connectFactoryObservable` from inside a functional component.

I think that we should create a ESLint rule so that developers don't fall for that mistake. Any volunteers? cough @voliva cough

I _think_ that as a first implementation something that just checks that the connector functions are being called from the "root scope" (not inside a function) should be enough? :thinking: 

Also, I think that the ESLint rule should be an error, not a warning.

**Comment by voliva** [comment]
Sure, I'll give it a go this afternoon!

**Comment by voliva** [comment]
I've been playing with ESLint and AST for a bit and I got something working

![image](https://user-images.githubusercontent.com/5365487/86183996-8528ef00-bb33-11ea-8e6d-c5c968bcff33.png)

At the moment what it does is just check that the function call is not happening inside a function or a class. It also handles:
* `import { connectObservable as co } from 'react-rxjs'` and then using co inside a component.
* `import * as ReactRxJS from 'react-rxjs'` and then calling `ReactRxJS.connectObservable`.
* It won't show up an error if `connectObservable` is being called without importing it (e.g. the consumer has defined a function with that name)

I tried pushing the code so far to the `re-rxjs` organization but I couldn't - so I created the repo in my account: https://github.com/voliva/eslint-plugin-react-rxjs. Happy to move it when we feel it's ready to publish 🚀. It would be great to have some feedback on what's in so far.

**Comment by josepot** [comment]
This is awesome! Thanks a lot @voliva !

> I tried pushing the code so far to the re-rxjs organization but I couldn't

:thinking: I can see that you created a private-repo under the org:

![image](https://user-images.githubusercontent.com/8620144/86189720-aba25680-bb42-11ea-92fe-9189f8cd95e7.png)

but you can't push to it? Weird... I will look into the settings to make sure that you can do these things.

**Comment by josepot** [comment]
It looks awesome, my only reservation is with the name of the rule... I think that instead of `connect-in-components` it should be named `no-connect-in-components`. I think that name is a bit more consistent with other standard eslint-rules, e.g. `no-await-in-loop`, `no-console`, `no-import-assign`, etc

**Comment by josepot** [comment]
It's so weird that you weren't able to push the code... Anyways, I have made the repo public, then I have put the commit-history of your personal repo into that one, and then I've [opened this PR.](https://github.com/re-rxjs/eslint-plugin-react-rxjs/pull/1)

**Comment by josepot** [comment]
I'm closing this issue, let's continue the conversation in that PR/repo. Once again, thanks a lot @voliva !
