### ISSUE TITLE
Move suspense utilities to utils package?

### ISSUE THREAD

**Issue by voliva** [re-rxjs/react-rxjs#81]
While writing the documentation I'm wondering about the suspense utility functions (suspend, suspended and switchMapSuspended) if they should be moved to `@react-rxjs/utils` instead of core.

I remember we discussed this and I think I was in favour of keeping them into `@react-rxjs/core`. However, now I see that maybe `core` should only export functions/values which can't be replaced externally (as the case of `SUSPEND` - that's a _core_ part of react-rxjs). But these operators are basically sugar to have something more declarative and ready-to-use.

**Comment by josepot** [comment]
I agree, let's move them to `@react-rxjs/utils`
