### ISSUE TITLE
I failed to create a counter

### ISSUE THREAD

**Issue by joshribakoff** [re-rxjs/react-rxjs#99]
```
ReactDOM.unstable_createRoot(
  document.getElementById('root')
).render(<Suspense fallback={<>wait</>}><App /></Suspense>);

function App() {
  const [useCounter] = connectObservable(interval(1000));
  const count = useCounter();
  return <div className="App">count {count}</div>;
}
```

It just says "wait". I can't get anything to work, except an initial value or initial suspend... Am I doing something wrong?

**Comment by josepot** [comment]
Hi @joshribakoff,

Our fault for not having documented things properly yet. 

> Am I doing something wrong?

Unfortunately yes :slightly_smiling_face: the hook is meant to be created outside of the component :wind_chime:

Like this:

```tsx
import {bind} form "@react-rxjs/core"

ReactDOM.unstable_createRoot(
  document.getElementById('root')
).render(<Suspense fallback={<>wait</>}><App /></Suspense>);

const [useCounter] = bind(interval(1000));

function App() {
  const count = useCounter();
  return <div className="App">count {count}</div>;
}
```

We are currently working on our docs site, and if everything goes well we will publish it this coming Tuesday. On the "getting started section" we will recommend installing this [eslint plugin](https://github.com/re-rxjs/eslint-plugin-react-rxjs) which detects this mistake. Although, if you want to see a WIP version of the getting started section, [please have a look at this](https://re-rxjs.github.io/react-rxjs.org/docs/);

**Comment by joshribakoff** [comment]
Thanks, that fixed it!
